---
- hosts: all
  tasks:
    - name: get the latest env flag file
      find:
        paths: "/home/oracle/AUTO_LOGS/BounceApps/VASPAT"
        file_type: file
        patterns: "VASPAT.flags"
        recurse: yes
      become_user: oracle
      register: file_flag

    - set_fact:
        latest_file: "{{ file_flag.files | sort(attribute='mtime',reverse=true) | first }}"
        
    - debug:
        msg="{{ latest_file }}"

